controller_list:
  - name: fake_arm_controller
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Joint6
      - Joint7
#  - name: fake_gripper_controller
#    joints:
#      - Joint_finger1
#      - Joint_finger2
#  - name: fake_arms_controller
#    joints:
#      - Joint1
#      - Joint2
#      - Joint3
#      - Joint4
#      - Joint5
#      - Joint6
#      - Joint7
#      - Joint_finger1
#      - Joint_finger2
